name: Build for NX

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'config.sample.txt'
      - 'assets/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'config.sample.txt'
      - 'assets/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "DEVKITPPC=/opt/devkitpro/devkitPPC" >> $GITHUB_ENV
          echo "DEVKITA64=/opt/devkitpro/devkitA64" >> $GITHUB_ENV

      - name: Build with make
        run: make build
